---
name: Build disk images

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ... # [ubunu-24.04|ubunu-24.04-arm]
    container: 
      image: ghcr.io/gbraad-actions/fedora:stable
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: gbraad-actions/start-tailscale@v1
        with:
          run: |
            dnf install -y just jq podman && just build-iso
       - uses: actions/upload-artifact@v7.0.1
          with:
            path: | 
              output
